import { useState } from 'react'
import { Sparkles, X } from 'lucide-react'
import { cn } from '@/lib/utils'

interface AiDisclaimerProps {
  /** Short label for the type of content, e.g. "marketing copy", "run-of-show timeline" */
  contentType?: string
  /** Extra class names for the wrapper */
  className?: string
  /** If true, the user can dismiss the banner and it will not reappear this session */
  dismissible?: boolean
}

/**
 * Lightweight banner that marks AI-generated content.
 *
 * Place this at the top of any section where content was generated by AI
 * so property managers know to review it before sharing with residents.
 */
export function AiDisclaimer({
  contentType = 'content',
  className,
  dismissible = true,
}: AiDisclaimerProps) {
  const [dismissed, setDismissed] = useState(false)

  if (dismissed) return null

  return (
    <div
      role="note"
      aria-label="AI-generated content notice"
      className={cn(
        'flex items-start gap-2.5 rounded-lg border border-amber-200 bg-amber-50 px-3 py-2.5 text-amber-800',
        'dark:border-amber-800/40 dark:bg-amber-900/20 dark:text-amber-300',
        className,
      )}
    >
      <Sparkles className="h-4 w-4 shrink-0 mt-0.5 text-amber-500" aria-hidden="true" />
      <p className="flex-1 text-xs leading-relaxed">
        <span className="font-semibold">AI-generated {contentType}.</span>{' '}
        Review and edit before sharing with residents — AI suggestions may
        contain errors or need customisation for your building.
      </p>
      {dismissible && (
        <button
          type="button"
          onClick={() => setDismissed(true)}
          aria-label="Dismiss AI notice"
          className="shrink-0 -mr-0.5 rounded p-0.5 hover:bg-amber-100 dark:hover:bg-amber-800/30 transition-colors"
        >
          <X className="h-3.5 w-3.5" />
        </button>
      )}
    </div>
  )
}
